### ISSUE TITLE
Builded release?

### ISSUE THREAD

**Issue by ghost** [JustIntroverted/TaskbarCustomizer#9]
hello

I'm not a win dev... why not release a compiled version for other devs?

**Comment by JustIntroverted** [comment]
I'm not sure what you're asking. There's a release of the latest update:

https://github.com/JustIntroverted/TaskbarCustomizer/releases/tag/v0.1.18-alpha

**Comment by ghost** [comment]
🤦🏻 I'm stupid... correct. hahaha
